repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]
  - repo: local
    hooks:
      - id: pyrefly
        name: pyrefly
        language: system
        entry: uv run pyrefly check
        args: [src/mysk]
        pass_filenames: false
      - id: pytest
        name: pytest
        language: system
        entry: uv run pytest
        pass_filenames: false
